### ISSUE TITLE
Forks Are Excluded

### ISSUE THREAD

**Issue by umutphp** [teoxoy/profile-readme-stats#2]
Hi @teoxoy,

Many thanks for this great action :)

The action excludes the forked repositories while calculating the stats. I personally think that there are may be forked repositories which may worth to mention in the profile (in terms of count and stars). So, what do you think about stopping to exclude forks? 

Or an input can bu added to the action to include this kind of repositories.

**Comment by teoxoy** [comment]
One idea I had is to calculate the stars relative to the users contribution to that repo. This is not yet possible because of a bug in Github's GraphQL API (I reported it, they are working on it).

When it comes to count of repos, I didn't want to include forks because usually you would fork a repo, commit and then put up a PR on the original. This would in turn double the nr of repos which to me seems like artificially inflating the number.

**Comment by umutphp** [comment]
Many thanks for the quick reply :).

You are mostly right about the PR flow but also there are some exceptional cases. One case is the translation repositories of articles, lists or e-books. For example, I am managing the [Turkish translation](https://github.com/umutphp/hacker-laws-tr) of [Hacker Laws repository](https://github.com/dwmkerr/hacker-laws). The fork will never be put up as a PR to the main repository.

**Comment by teoxoy** [comment]
Oh, makes sense.
Would you like to put up a PR for this?
It would consist of adding an option (`includeForks`) to the action.

**Comment by umutphp** [comment]
I would really like to do but I am not good at JS and TS.

**Comment by teoxoy** [comment]
@umutphp fixed some stuff in the PR and merged it
Let me know if it works as expected!

**Comment by umutphp** [comment]
Hi @teoxoy ,

Many thanks for the quick action :). The code is working as expected.
